/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['js/compute.js']) {
  _$jscoverage['js/compute.js'] = [];
  _$jscoverage['js/compute.js'][1] = 0;
  _$jscoverage['js/compute.js'][2] = 0;
  _$jscoverage['js/compute.js'][3] = 0;
  _$jscoverage['js/compute.js'][5] = 0;
  _$jscoverage['js/compute.js'][8] = 0;
  _$jscoverage['js/compute.js'][9] = 0;
  _$jscoverage['js/compute.js'][10] = 0;
  _$jscoverage['js/compute.js'][12] = 0;
}
_$jscoverage['js/compute.js'].source = ["<span class=\"k\">function</span> add<span class=\"k\">(</span>a<span class=\"k\">,</span>b<span class=\"k\">)</span><span class=\"k\">{</span>","\t<span class=\"k\">if</span><span class=\"k\">(</span>a <span class=\"k\">+</span> b <span class=\"k\">&gt;</span> <span class=\"s\">0</span><span class=\"k\">)</span>","\t\t<span class=\"k\">return</span> <span class=\"k\">true</span><span class=\"k\">;</span>","\t<span class=\"k\">else</span>","\t\t<span class=\"k\">return</span> <span class=\"k\">false</span><span class=\"k\">;</span>","<span class=\"k\">}</span>","","<span class=\"k\">function</span> reduc<span class=\"k\">(</span>a<span class=\"k\">,</span>b<span class=\"k\">)</span><span class=\"k\">{</span>","\t<span class=\"k\">if</span><span class=\"k\">(</span>a <span class=\"k\">-</span> b <span class=\"k\">&gt;</span> <span class=\"s\">0</span><span class=\"k\">)</span>","\t\t<span class=\"k\">return</span> <span class=\"k\">true</span><span class=\"k\">;</span>","\t<span class=\"k\">else</span>","\t\t<span class=\"k\">return</span> <span class=\"k\">false</span><span class=\"k\">;</span>","<span class=\"k\">}</span>"];
_$jscoverage['js/compute.js'][1]++;
function add(a, b) {
  _$jscoverage['js/compute.js'][2]++;
  if (((a + b) > 0)) {
    _$jscoverage['js/compute.js'][3]++;
    return true;
  }
  else {
    _$jscoverage['js/compute.js'][5]++;
    return false;
  }
}
_$jscoverage['js/compute.js'][8]++;
function reduc(a, b) {
  _$jscoverage['js/compute.js'][9]++;
  if (((a - b) > 0)) {
    _$jscoverage['js/compute.js'][10]++;
    return true;
  }
  else {
    _$jscoverage['js/compute.js'][12]++;
    return false;
  }
}
